package com.androskin.androscan.enums;

public enum EnumDialogValues {
    EXIT_APP,
    MESSAGE,
    SAVE_SETTINGS,
    DOWNLOAD_GOODS,
    UPLOAD_DOCUMENT,
    CREATE_NEW_DOCUMENT,
    DELETE_DOCUMENT,
    DELETE_DOCUMENT_CONFIRM,
    DOCUMENT_ITEM_DETAILS,
    DELETE_DOCUMENT_ITEM,
    SET_NEW_ITEM_COUNT,
    DELETE_ITEM_FROM_DOCUMENT_GOODS
}
